export const courses = [
    'Computer Programming 1 (Labaratory/lecture)',
    'Introduction to Computing (Labaratory/Lecture)',
    'Mathemathics in Modern world',
    'National Service Training Program 1',
    'Physical Education 1',
    'Purposive Communication',
    'Understanding The Self',
    'Fundamental Of Information System',
    'Computer Programming 2 (Labaratory/Lecture)',
    'Discrete Math',
    'Readings In Philippine History',
    'Ethics',
    'National Service Training Program 2',
    'Physical Education 2',
    'Data Structure & algorithm Analysis',
    'The Contemporary World',
    'Science, Technology & Society',
    'Web Application & Design',
    'IT Infrastructure & Network Technologies',
    'Organization & Management Concepts',
    'Physical Education 3',
    'Database Management System',
    'Data Communication And Networking',
    'Professional Issues in IS',
    'Financial Management',
    'Environmental Science',
    'Physical Education 4',
    'Professional Elective 1 (IT Service Management)',
    'IS Strategy, Management and Acquisition',
    'Applications Development and Emerging Technologies (Lecture)',
    'Applications Development and Emerging Technologies (Laboratory)',
    'Human Computer Interaction',
    'Art Appreciation',
    'Business Etiquette and Social Races Training',
    'Professional Elective 4 (IS Innovations and New Technologies)',
];